#!/bin/bash

# Automated setup script for Numbas LTI Provider
# This script helps automate the initial deployment

set -e

echo "================================================"
echo "Numbas LTI Provider - Automated Setup"
echo "================================================"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo "Please run as root (use sudo)"
    exit 1
fi

# Function to prompt for input with default value
prompt_input() {
    local prompt="$1"
    local default="$2"
    local result
    
    if [ -n "$default" ]; then
        read -p "$prompt [$default]: " result
        result="${result:-$default}"
    else
        read -p "$prompt: " result
    fi
    
    echo "$result"
}

echo "Step 1: Configuration"
echo "--------------------"

# Get configuration values
DOMAIN=$(prompt_input "Enter your domain name (e.g., numbas.yourdomain.com)" "")
INSTANCE_NAME=$(prompt_input "Enter instance name" "Numbas LTI Provider")
ADMIN_USER=$(prompt_input "Admin username" "admin")
ADMIN_PASSWORD=$(prompt_input "Admin password (strong password recommended)" "")
SUPPORT_EMAIL=$(prompt_input "Support email address" "support@$DOMAIN")
DB_PASSWORD=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32)

echo ""
echo "Step 2: Checking Prerequisites"
echo "--------------------"

# Check if Docker is installed
if ! command -v docker &> /dev/null; then
    echo "Docker not found. Installing Docker..."
    
    # Install prerequisites
    apt update
    apt install -y ca-certificates curl gnupg lsb-release
    
    # Add Docker GPG key
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    
    # Add Docker repository
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    
    # Install Docker
    apt update
    apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    
    echo "✓ Docker installed successfully"
else
    echo "✓ Docker is already installed"
fi

# Check if certbot is installed
if ! command -v certbot &> /dev/null; then
    echo "Installing Certbot for SSL certificates..."
    apt install -y certbot
    echo "✓ Certbot installed"
else
    echo "✓ Certbot is already installed"
fi

echo ""
echo "Step 3: SSL Certificate"
echo "--------------------"

SSL_OPTION=$(prompt_input "SSL Certificate: (1) Let's Encrypt, (2) Self-signed" "1")

mkdir -p files/ssl

if [ "$SSL_OPTION" = "1" ]; then
    echo "Obtaining Let's Encrypt certificate for $DOMAIN..."
    echo "Note: Make sure your domain DNS is pointing to this server!"
    read -p "Press Enter to continue..."
    
    # Stop any service that might be using port 80/443
    systemctl stop apache2 2>/dev/null || true
    systemctl stop nginx 2>/dev/null || true
    
    certbot certonly --standalone -d "$DOMAIN" --non-interactive --agree-tos --email "$SUPPORT_EMAIL"
    
    # Copy certificates
    cp "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" files/ssl/numbas-lti.pem
    cp "/etc/letsencrypt/live/$DOMAIN/privkey.pem" files/ssl/numbas-lti.key
    
    echo "✓ Let's Encrypt certificate obtained"
    
    # Setup auto-renewal script
    cat > /etc/cron.monthly/renew-numbas-ssl.sh << 'CRONEOF'
#!/bin/bash
certbot renew --quiet
cp /etc/letsencrypt/live/DOMAIN_PLACEHOLDER/fullchain.pem /opt/numbas-lti-provider-docker/files/ssl/numbas-lti.pem
cp /etc/letsencrypt/live/DOMAIN_PLACEHOLDER/privkey.pem /opt/numbas-lti-provider-docker/files/ssl/numbas-lti.key
cd /opt/numbas-lti-provider-docker && docker compose restart nginx
CRONEOF
    sed -i "s/DOMAIN_PLACEHOLDER/$DOMAIN/g" /etc/cron.monthly/renew-numbas-ssl.sh
    chmod +x /etc/cron.monthly/renew-numbas-ssl.sh
    echo "✓ Auto-renewal script created"
    
else
    echo "Generating self-signed certificate..."
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
      -keyout files/ssl/numbas-lti.key \
      -out files/ssl/numbas-lti.pem \
      -subj "/C=US/ST=State/L=City/O=Organization/CN=$DOMAIN"
    echo "✓ Self-signed certificate generated"
fi

chmod 644 files/ssl/numbas-lti.pem
chmod 600 files/ssl/numbas-lti.key

echo ""
echo "Step 4: Creating Configuration File"
echo "--------------------"

cat > settings.env << EOF
# Generated by setup script on $(date)

SERVERNAME=$DOMAIN
INSTANCE_NAME=$INSTANCE_NAME
LANGUAGE_CODE=en
TIME_ZONE=UTC

SUPERUSER_USER=$ADMIN_USER
SUPERUSER_PASSWORD=$ADMIN_PASSWORD

DEFAULT_FROM_EMAIL=noreply@$DOMAIN
SUPPORT_NAME=Technical Support
SUPPORT_URL=mailto:$SUPPORT_EMAIL

EMAIL_COMPLETION_RECEIPTS=False

LOGLEVEL=WARNING
POSTGRES_PASSWORD=$DB_PASSWORD

SECRET_KEY=WILL_BE_GENERATED

NUMBAS_LOCKDOWN_APP_PASSWORD=

REPORT_SCORE_SUBTRACT_MINUTES=1
AUTOMATIC_SCORE_REPORT_DELAY_MINUTES=5
EOF

echo "✓ Configuration file created"

echo ""
echo "Step 5: Building Docker Image"
echo "--------------------"

docker build . -t numbas/numbas-lti-provider
echo "✓ Docker image built"

echo ""
echo "Step 6: Generating Secret Key"
echo "--------------------"

SECRET_KEY=$(docker compose run --rm numbas-setup python ./get_secret_key 2>/dev/null | tail -1)
sed -i "s/SECRET_KEY=WILL_BE_GENERATED/SECRET_KEY=$SECRET_KEY/" settings.env
echo "✓ Secret key generated and saved"

echo ""
echo "Step 7: Running Installation"
echo "--------------------"

docker compose run --rm numbas-setup python ./install
echo "✓ Installation completed"

echo ""
echo "Step 8: Configuring Firewall"
echo "--------------------"

if command -v ufw &> /dev/null; then
    ufw allow 443/tcp
    ufw allow 80/tcp
    ufw allow 22/tcp
    echo "y" | ufw enable 2>/dev/null || true
    echo "✓ Firewall configured"
else
    echo "! UFW not found, please configure firewall manually"
fi

echo ""
echo "Step 9: Starting Services"
echo "--------------------"

docker compose up -d --scale daphne=4 --scale huey=1
echo "✓ Services started"

echo ""
echo "================================================"
echo "Installation Complete!"
echo "================================================"
echo ""
echo "Your Numbas LTI Provider is now running at:"
echo "  https://$DOMAIN"
echo ""
echo "Login credentials:"
echo "  Username: $ADMIN_USER"
echo "  Password: $ADMIN_PASSWORD"
echo ""
echo "Database password (save this): $DB_PASSWORD"
echo ""
echo "Useful commands:"
echo "  View logs:    docker compose logs -f"
echo "  Stop:         docker compose down"
echo "  Start:        docker compose up -d --scale daphne=4 --scale huey=1"
echo "  Check status: docker compose ps"
echo ""
echo "Please change your admin password after first login!"
echo "================================================"
